### ISSUE TITLE
Miscellaneous

### ISSUE THREAD

**Issue by capitanevs** [oasys-elettra-kit/WISEr#2]
We should refurbish the code like that
DOWNSTREAM_FOCUS 
instead of
DowstreamFocus

![immagine](https://user-images.githubusercontent.com/13431660/62132695-d0ac9a80-b2dd-11e9-90ef-78198a5875f7.png)

**Comment by aljosahafner** [comment]
Ok, I will get to work on this tomorrow. This is in Fundation.py? Maybe we can rename the function into Foundation.py (if it's meant to mean what this word means)...
