### ISSUE TITLE
Foundation. GeneralDistanceFromParent

### ISSUE THREAD

**Issue by capitanevs** [oasys-elettra-kit/WISEr#31]
Two comments on that.

**a)** As an (untold) convention, I used to name attributes so that **properties** sound like **nouns**, while **methods(i.e. functions)** sound like **verbs**. Since `GeneralDistanceFromParent(self, Orientation=True, Reference=True):`, is a function,  it shall be renamed with **Get** 
`GetGeneralDistanceFromParent`. **BUT... (see b)**

**b)** As another (untold) convention that I used, more specific functions are marked by "appending" labels describing features. E.g. `MirrorElliptic`, `MirrorPlane` and not `EllipticMirror`, `PlaneMirror`. The reason is simple: it sounds "bad English", but it makes programming easier and tidier. For instance, with autocompletion you type "Mirror..." and then you get all the "Mirror-ware". 
I would do the same for yout function.
So  `GetGeneralDistanceFromParent` => `GetDistanceFromParentGeneral`

**Disclaimer**  "Convention" is a big word. Let's call it "guideline".
  
**c)** We should keep only one function for getting the distance in the future. Which is the best one? `GetDistanceFromParent ` or `GetDistanceFromParentGeneral`? 
We are not deciding now, but every time that we will use a new "GetDistanceFromParent..." we will discuss which one to use. It "general" is the best, we will replace it everywhere little by little.

**Comment by aljosahafner** [comment]
def GetDistanceFromParent(self, SameOrientation=False, OnlyReference=False):
result = self.DistanceFromSource - self.GetParent(SameOrientation=SameOrientation, OnlyReference=OnlyReference).DistanceFromSource

def GeneralDistanceFromParent(self, Orientation=True, Reference=True):
distance = np.linalg.norm(self.XYCentre - self.GetParent(SameOrientation=Orientation, OnlyReference=Reference).XYCentre)

We can use the second case in GetDIstanceFromParent and delete GeneralDistanceFromParent

**Comment by capitanevs** [comment]
In which case `GeneralDistanceFromParent` is supposed to work whereas ` GetDistanceFromParent`  is not? Can you remember that?

Notice: ` GetDistanceFromParent` shall be called after that PositioningDirectives have been Refreshed, in any case.
I did not do a control structure for that (I did not have time)
**something like:**. a variable `BeamlineElements.UpdatedPositioningDirectives =True|False`, then every time that you change positioning directives or add/append an element, you switch it to False. If you call `ApplyPositioningDirectives()` it is switched to `True`. 

Then, functions such as `GetDistanceFromParent` have an `if UpdatedPositioningDirectives is True` sentence to perform a control, to check if it makes sense to compute the distance.

Of course we have more important work to do now, but probably this is how I should have done it.
